# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-and-Unit-Tests:

    runs-on: ubuntu-latest

   

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies  
      run: npm ci
    - name: Unit-Tests  
      run: npm run test:unit
    - name: Dispaly MY User Name
      run:  echo "@VPP88"  

  UI-Tests:
    needs: Build-and-Unit-Tests
    runs-on: ubuntu-latest
    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies  
      run: npm ci
    - name: Install browsers
      run: npx playwright install 
    - name: Run Application
      run: npm run start &    
    - name: Run UI Tests  
      run: npm run test:ui
    - name: Dispaly MY User Name
      run:  echo "@VPP88" 
  Deploy-To-Render:
    needs: UI-Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true   
      - name: Dispaly MY User Name
        run:  echo "@VPP88"    
